// <auto-generated />
using Bookstore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bookstore.Infrastructure.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20200120120742_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bookstore.Core.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Elizabeth",
                            LastName = "Gilbert"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Alex",
                            LastName = "Michaelides"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jayson",
                            LastName = "Greene"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Jennifer",
                            LastName = "Weiner"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Yangsze",
                            LastName = "Choo"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Taylor",
                            LastName = "Jenkins Reid"
                        });
                });

            modelBuilder.Entity("Bookstore.Core.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Name = "City of Girls",
                            Price = 100m,
                            Year = 1911
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            Name = "The Silent Patient",
                            Price = 400m,
                            Year = 1991
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 3,
                            Name = "Once More We Saw Stars",
                            Price = 500m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 1,
                            Name = "Mrs. Everything",
                            Price = 2000m,
                            Year = 1971
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 1,
                            Name = "The Night Tiger",
                            Price = 20m,
                            Year = 1981
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            CategoryId = 1,
                            Name = "Daisy Jones & The Six",
                            Price = 200m,
                            Year = 2000
                        });
                });

            modelBuilder.Entity("Bookstore.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Novel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Memoir"
                        });
                });

            modelBuilder.Entity("Bookstore.Core.Entities.Book", b =>
                {
                    b.HasOne("Bookstore.Core.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bookstore.Core.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
